# Generated by Django 3.0.2 on 2020-01-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stvar', '0002_auto_20200116_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stvar',
            name='slika',
            field=models.FileField(upload_to=''),
        ),
    ]
