# Generated by Django 3.1.5 on 2021-01-06 00:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stvar', '0003_auto_20200118_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stvar',
            name='slika',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Ocene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('korisnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stvar.stvar')),
            ],
        ),
    ]
